/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cly753_process_NotAlgoCpp */

#ifndef _Included_cly753_process_NotAlgoCpp
#define _Included_cly753_process_NotAlgoCpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cly753_process_NotAlgoCpp
 * Method:    Extract
 * Signature: ([BIII)I
 */
JNIEXPORT jint JNICALL Java_cly753_process_NotAlgoCpp_Extract
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
