// public class NotPartitioner extends Partitioner<Text, NotFeatureWritable> {
//     @Override
//     public int getPartition(Text key, NotFeatureWritable value, int numPartitions) {
//         ...
//         ...
//         ...
//         return /* partition index */; // [0, numPartitions)
//     }
// }