/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cly753_process_BFLoG_API */

#ifndef _Included_cly753_process_BFLoG_API
#define _Included_cly753_process_BFLoG_API
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cly753_process_BFLoG_API
 * Method:    Extract
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_cly753_process_BFLoG_1API_Extract
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
