/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Wrap */

#ifndef _Included_Wrap
#define _Included_Wrap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Wrap
 * Method:    sayHi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Wrap_sayHi
  (JNIEnv *, jobject);

/*
 * Class:     Wrap
 * Method:    process
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_Wrap_process
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
