/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BFLoG_API */

#ifndef _Included_BFLoG_API
#define _Included_BFLoG_API
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BFLoG_API
 * Method:    Extract
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_BFLoG_1API_Extract
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
